#define TILEGXPCI_MAJOR 10
#define TILEGXPCI_MINOR 0

#define STRIFY(X) #X
#define MAKE_VERSION_STRING(MAJOR, MINOR) \
  STRIFY(MAJOR) "." STRIFY(MINOR) "-4.2.3.172691"

#define TILEGXPCI_VERSION_STRING \
  MAKE_VERSION_STRING(TILEGXPCI_MAJOR, TILEGXPCI_MINOR)

#define LICENSE_STRING "GPL"
